grafana:
  adminPassword: admin
  ingress:
    enabled: true
    hosts:
      - grafana.ahmadrezadomain.com
  service:
    type: LoadBalancer

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false